name: SmartExpiryTracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  path: ^1.8.3
  shared_preferences: ^2.5.3
#  for local notification
  flutter_local_notifications: ^19.2.0
  timezone: ^0.10.1
  permission_handler: ^12.0.0+1
  android_intent_plus: ^5.3.0
  device_info_plus: ^11.4.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.3
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
  fonts:
    - family: primary
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: secondary
      fonts:
        - asset: assets/fonts/Exo-Regular.ttf
